version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.1.3
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - my-network
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.1.3
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rocketmq/broker.conf:/home/rocketmq/rocketmq-5.1.3/conf/broker.conf
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - my-network
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.1.3/conf/broker.conf
  proxy:
    image: apache/rocketmq:5.1.3
    container_name: rmqproxy
    networks:
      - my-network
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rmqdashboard
    ports:
      - 9099:8080  # 修改宿主机端口为9090，容器内端口保持8080不变
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=192.168.124.21:9876
    depends_on:
      - namesrv
    networks:
      - my-network
networks:
  my-network:
    driver: bridge